services:
  db:
    image: postgres:alpine
    user: postgres
    container_name: db
    environment:
      POSTGRES_USER: cosyl
      POSTGRES_PASSWORD: cosyl
      POSTGRES_DB: explorer-test
      PGPORT: "5433"
    expose:
      - "5433"
    volumes:
      - pgdata_explorer_test:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U cosyl -d explorer-test && psql -U cosyl explorer-test" ]
      interval: 5s
      timeout: 3s
      retries: 10

  backend:
    container_name: backend
    build: .
    depends_on:
      db:
        condition: service_healthy
    ports:
     - ${PORT}:${PORT}
    env_file:
     - ./.secrets
    environment:
      DATABASE_URL: "postgres://cosyl:cosyl@db:5433/explorer-test"
      PORT: "3046"
      DB_PORT: "5433"
      DEBUG: "false"
      API_MODE: "dev"
      RUN_FIXTURES: "true"
      FIXTURES_PATH: "test.yml"
    tmpfs:
      - /tmp

  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: tests/Dockertest.next.front
    env_file:
      - ./www/.env.docker
    depends_on:
      - backend
    ports:
     - 3000:3000

volumes:
  pgdata_explorer_test:
