import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { GlobalNav } from "components/GlobalNav";
import { FiltersBar } from "components/FiltersBar";
import Container from "react-bootstrap/Container";
import Row from "react-bootstrap/Row";
import Col from "react-bootstrap/Col";

import TagsFiltersBar from "components/TagFiltersBar";
import SyllabusCard from "components/SyllabusCard";

const Collection: NextPage = () => {
  return (
    <div className="container">
      <Head>
        <title>Collection Name</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div id="header-section" className="sticky-top">
        <GlobalNav />
        <FiltersBar />
      </div>

      <Container>
        <Row className="d-flex flex-row-reverse">
          <h1>This is a collection page.</h1>
        </Row>
      </Container>
    </div>
  );
};

export default Collection;
