import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { GlobalNav } from "components/GlobalNav";
import { FiltersBar } from "components/FiltersBar";
import Container from "react-bootstrap/Container";
import Row from "react-bootstrap/Row";
import Col from "react-bootstrap/Col";

import TagsFiltersBar from "components/TagFiltersBar";
import SyllabusCard from "components/SyllabusCard";
import { BreadcrumbsBar } from "components/BreadcrumbsBar";

const Collection: NextPage = () => {
  return (
    <div className="container">
      <Head>
        <title>Collection Name</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div id="header-section" className="sticky-top">
        <GlobalNav />
        <BreadcrumbsBar />
      </div>

      <Container>
        <Row className="pt-3 pb-3">
          <h1>Web Design History</h1>
          <p class="collection-description">
            Lorem ipsum a collection about web design, with discussions on
            historical and current interaction design precedents.
          </p>
        </Row>
        <Row className="gap-3 pb-5">
          <SyllabusCard />
          <SyllabusCard />
          <SyllabusCard />
          <SyllabusCard />
          <SyllabusCard />
        </Row>
      </Container>
    </div>
  );
};

export default Collection;
