import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { GlobalNav } from "components/GlobalNav";
import Container from "react-bootstrap/Container";
import Row from "react-bootstrap/Row";
import Col from "react-bootstrap/Col";

import { FiltersBar } from "components/FiltersBar";
import TagsFiltersBar from "components/TagFiltersBar";
import SyllabusCard from "components/SyllabusCard";

const Home: NextPage = () => {
  return (
    <div className="container">
      <Head>
        <title>Syllabi Explorer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="sticky-top header-section">
        <GlobalNav />
        <FiltersBar />
      </div>

      <Container>
        <Row className="d-flex flex-row-reverse">
          <Col lg={4} className="border-start">
            <TagsFiltersBar />
          </Col>
          <Col className="pt-3 pb-5 d-flex flex-column gap-3">
            <SyllabusCard />
            <SyllabusCard />
            <SyllabusCard />
            <SyllabusCard />
            <SyllabusCard />
            <SyllabusCard />
          </Col>
        </Row>
      </Container>
    </div>
  );
};

export default Home;
