import type { NextPage } from "next";
import Head from "next/head";
import { GlobalNav } from "components/GlobalNav";
import Container from "react-bootstrap/Container";
import Row from "react-bootstrap/Row";
import Col from "react-bootstrap/Col";
import Button from "react-bootstrap/Button";

import SyllabusBreadcrumbs from "components/SyllabusBreadcrumbs";
import SyllabusSchoolCodeYear from "components/Syllabus/SyllabusSchoolCodeYear";
import SyllabusFooter from "components/Syllabus/SyllabusFooter";

const Syllabus: NextPage = () => {
  return (
    <div className="container">
      <Head>
        <title>Web Design Basics</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div id="header-section" className="sticky-top">
        <GlobalNav />
        <SyllabusBreadcrumbs />
      </div>
      <Container>
        <Row className="d-flex justify-content-center">
          <Col className="pt-3 pb-5 d-flex flex-column gap-3" lg={10}>
            <SyllabusSchoolCodeYear
              institution="Parson The New School of Design"
              code="PSAM1028"
              year="Spring 2019"
            />
            <h1 className="p-0 m-0">Web Design Basics</h1>
            <p className="course-instructors p-0 m-0">Pat Shiu</p>
            <div className="course-tags d-flex gap-2">
              <Button className="btn-sm btn-tag">web design</Button>
              <Button className="btn-sm btn-tag">foundation</Button>
              <Button className="btn-sm btn-tag">undergraduate</Button>
            </div>
            <h2>Course Overview</h2>
            <p className="course-description">
              Web Design Basics is designed to introduce students to programming
              as a creative medium—as a way of making and exploring. The
              coursework focuses on developing a vocabulary of interaction
              design principles which can then be applied across a range of
              platforms. Students are encouraged to experiment with various
              media, tools, and techniques, ultimately producing a portfolio of
              interactive and visual projects designed for the screen. An
              emphasis is placed on typography as it applies to a screen
              context, research-based problem solving and a “learning through
              making” approach to technical skill building. Historical and
              current interaction design precedents will be discussed.
            </p>
            <h2>Related Resources</h2>
            <SyllabusFooter
              instructors="Pat Shiu"
              author="Pat Shiu"
              uploadDate="May 24, 2022"
            />
          </Col>
        </Row>
      </Container>
    </div>
  );
};

export default Syllabus;
