package models

var LEVELS = map[int]string{
	0: "Other",
	1: "Bachelor",
	2: "Master",
	3: "Doctoral",
}

// https://qa.auth.gr/documents/ISCED/ISCED-F.pdf
var ACADEMIC_FIELDS = map[int]string{
	000: "Generic",
	001: "Basic programmes and qualifications",
	002: "Literacy and numeracy",
	003: "Personal skills and development",

	100: "Education",
	11:  "Education",
	111: "Education sciences",
	112: "Training for pre-school teachers",
	113: "Teacher training without subject specialization",
	114: "Teacher training with subject specialization",

	200: "Arts and humanities",
	21:  "Arts",
	211: "Audio-visual techniques and media production",
	212: "Fashion, interior and industrial design",
	213: "Fine arts",
	214: "Handicrafts",
	215: "Music and performing arts",
	22:  "Humanities",
	221: "Religion and theology",
	222: "History and archeology",
	223: "Philosophy and ethics",
	231: "Language acquisition",
	232: "Literature and linguistics",

	300: "Social sciences, journalism and information",
	31:  "Social and behavioural sciences",
	311: "Economics",
	312: "Political sciences and civics",
	313: "Psychology",
	314: "Sociology and cultural studies",
	32:  "Journalism and information",
	321: "Journalism and reporting",
	322: "Library, information and archival studies",

	400: "Business, sdministration and law",
	41:  "Business and administration",
	411: "Accounting and taxation",
	412: "Finance, banking and insurance",
	413: "Management and administration",
	414: "Marketing and advertising",
	415: "Secretarial and office work",
	416: "Wholesale and retail sales",
	417: "Work skills",
	42:  "Law",
	421: "Law",

	500: "Natural sciences, mathematics and statistics",
	51:  "Biological and related sciences",
	511: "Biology",
	512: "Biochemistry",
	52:  "Environment",
	521: "Environmental sciences",
	522: "Natural environments and wildlife",
	53:  "Physical Sciences",
	531: "Chemistry",
	532: "Earth sciences",
	533: "Physics",
	54:  "Mathematics and sciences",
	541: "Mathematics",
	542: "Statistics",

	600: "Information and communication technologies",
	61:  "Information and Communication Technologies",
	611: "Computer use",
	612: "Database and network design and administration",
	613: "Software and application development and anaysis",

	700: "Engineering, manufacturing and construction",
	71:  "Engineering and engineering trades",
	711: "Chemical engineering and processes",
	712: "Environmental protextion technology",
	713: "Electricity and energy",
	714: "Electronics and automation",
	715: "Mechanics and metal trades",
	716: "Motor vehicles, ships and aircrafts",
	72:  "Manufacturing and processing",
	721: "Food processing",
	722: "Materials (glass, paper, plastic and wood)",
	723: "Textile (clothes, footwear, leather)",
	724: "Mining and extraction",
	73:  "Architecture and construction",
	731: "Architecture and town planning",
	732: "Building and civil engineering",

	800: "Agriculture, forestry, fisheries and veterinary",
	81:  "Agriculture",
	811: "Crop and livestock production",
	812: "Horticulture",
	82:  "Forestry",
	821: "Forestry",
	83:  "Fisheries",
	831: "Fisheries",
	84:  "Veterinary",
	841: "Veterinary",

	900: "Health and Welfare",
	91:  "Health",
	911: "Dental studies",
	912: "Medicine",
	913: "Nursing and midwifery",
	914: "Medical diagnostic and treatment technology",
	915: "Therapy and rehabilitation",
	916: "Pharmacy",
	917: "Traditional and complementary medicine and therapy",

	1000: "Services",
	101:  "Personal services",
	1011: "Domestic services",
	1012: "Hair and beauty services",
	1013: "Hotel, restaurants and catering",
	1014: "Sports",
	1015: "Travel, tourism, and leisure",
	102:  "Hygiene and occupational health services",
	1021: "Community sanitation",
	1022: "Occupational and health and safety",
	1031: "Military and defence",
	1032: "Protection of persons and property",
	104:  "Transport",
	1041: "Transportation services",
}
