import * as React from "react";

import type { GetServerSideProps, NextPage } from "next";
import Head from "next/head";

import Container from "react-bootstrap/Container";
import Row from "react-bootstrap/Row";
import Col from "react-bootstrap/Col";

import Favicons from "components/head/favicons";
import GlobalNav from "components/GlobalNav";
import TagsFiltersBar from "components/TagFiltersBar";
import { getSyllabusCards } from "../../components/utils/getSyllabusCards";
import { getCollectionCards } from "../../components/utils/getCollectionCards";

import { ICollection } from "types";

interface ICollectionsProps {
  collectionsListings: ICollection[];
}

export const getServerSideProps: GetServerSideProps = async () => {
  const apiUrl = process.env.NEXT_PUBLIC_API_URL;
  const url = require("node:url").resolve(apiUrl, "collections/");

  console.log(`COLLECTIONS FETCH URL: ${url}`);

  const res = (await fetch(url).catch((err) => {
    console.log(`error fetching backend: ${err}`);

    return {
      props: {
        collectionsListings: [],
      },
    };
  })) as Response;

  if (!res.ok) {
    return {
      props: {
        collectionsListings: [],
      },
    };
  } else {
  }
  const collectionsListings = await res.json();

  console.log(`FETCHED ${collectionsListings.length} COLLECTIONS`);
  return {
    props: {
      collectionsListings: collectionsListings,
    },
  };
};

const Collections: React.FunctionComponent<ICollectionsProps> = ({
  collectionsListings,
}) => {
  return (
    <>
      <Head>
        <title>Syllabi Explorer</title>
        <meta name="description" content="Generated by create next app" />
        <Favicons />
      </Head>

      <Container fluid id="header-section" className="sticky-top">
        <GlobalNav />
      </Container>
      <Container>
        <h1 className="pt-3">Public Collections</h1>
        <Row className="d-flex ">
          <Col lg={8} className="pt-3 pb-5 d-flex flex-column gap-3">
            {getCollectionCards(collectionsListings)}
          </Col>
        </Row>
      </Container>
    </>
  );
};

export default Collections;
